start cmd.exe /k "cd PATH\TO\FILE\LOCATION && node fileWriter.js"
start cmd.exe /k "cd PATH\TO\FILE\LOCATION && python mainx.py" 
start cmd.exe /k "cd PATH\TO\FILE\LOCATION && python justplots.py" 
start cmd.exe /k "cd PATH\TO\FILE\LOCATION && arduplane.exe -Mxplane -s1 --uartA tcp:0"
start cmd.exe /k "cd PATH\TO\FILE\LOCATION && MissionPlanner.exe"
